version: "3.4"

services:
  # Database
  bookstore-mysql-db:
    image: mysql:5.7
    container_name: bookstore-mysql-db
    hostname: bookstore-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: "bookstore_db"
      MYSQL_USER: "bookstoreDBA"
      MYSQL_PASSWORD: "PaSSworD"
      MYSQL_ROOT_PASSWORD: "r00tPaSSworD"

      #Connection Pool
      MYSQL_POOL_MAX_ACTIVE: '200'
      MYSQL_POOL_MAX_WAIT: '5000'
      MYSQL_POOL_MAX_IDLE: '20'
    ports:
      - "3306:3306"
    volumes:
      - bookstore-db-volume:/var/lib/mysql
    networks:
      - bookstore-app-network

  # Core services
  bookstore-consul-discovery:
    hostname: bookstore-consul-discovery
    image: hashicorp/consul
    container_name: bookstore-consul-discovery
    restart: always
    ports:
      - "8500:8500"
    networks:
      - bookstore-app-network
    deploy:
      placement:
        constraints: [node.role == manager]

  bookstore-zuul-api-gateway-server:
    build:
      context: ./bookstore-api-gateway-service
      args:
        JAR_FILE: bookstore-api-gateway-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/bookstore-zuul-api-gateway-server
    container_name: bookstore-zuul-api-gateway-server
    hostname: bookstore-zuul-api-gateway-server
    ports:
      - "8765:8765"
    networks:
      - bookstore-app-network
    environment:
      - SERVER_PORT=8765
      - ZIPKIN_HOST=bookstore-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      placement:
        constraints: [node.role == manager]

  bookstore-account-service:
    build:
      context: ./bookstore-account-service
      args:
        JAR_FILE: bookstore-account-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/bookstore-account-service
    container_name: bookstore-account-service
    hostname: bookstore-account-service
    ports:
      - "4001:4001"
    networks:
      - bookstore-app-network
    environment:
      - SERVER_PORT=4001
      - ZIPKIN_HOST=bookstore-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      labels:
        swarm.autoscaler: 'true'
        swarm.autoscaler.maximum: '4'
        swarm.autoscaler.minimum: '2'

  bookstore-billing-service:
    build:
      context: ./bookstore-billing-service
      args:
        JAR_FILE: bookstore-billing-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/bookstore-billing-service
    container_name: bookstore-billing-service
    hostname: bookstore-billing-service
    ports:
      - "5001:5001"
    networks:
      - bookstore-app-network
    environment:
      - SERVER_PORT=5001
      - ZIPKIN_HOST=bookstore-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      labels:
        swarm.autoscaler: 'true'
        swarm.autoscaler.maximum: '4'
        swarm.autoscaler.minimum: '1'

  bookstore-catalog-service:
    build:
      context: ./bookstore-catalog-service
      args:
        JAR_FILE: bookstore-catalog-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/bookstore-catalog-service
    container_name: bookstore-catalog-service
    hostname: bookstore-catalog-service
    ports:
      - "6001:6001"
    networks:
      - bookstore-app-network
    environment:
      - SERVER_PORT=6001
      - ZIPKIN_HOST=bookstore-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      labels:
        swarm.autoscaler: 'true'
        swarm.autoscaler.maximum: '4'
        swarm.autoscaler.minimum: '1'

  bookstore-order-service:
    build:
      context: ./bookstore-order-service
      args:
        JAR_FILE: bookstore-order-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/bookstore-order-service
    container_name: bookstore-order-service
    hostname: bookstore-order-service
    ports:
      - "7001:7001"
    networks:
      - bookstore-app-network
    environment:
      - SERVER_PORT=7001
      - ZIPKIN_HOST=bookstore-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      labels:
        swarm.autoscaler: 'true'
        swarm.autoscaler.maximum: '4'
        swarm.autoscaler.minimum: '1'

  bookstore-payment-service:
    build:
      context: ./bookstore-payment-service
      args:
        JAR_FILE: bookstore-payment-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/bookstore-payment-service
    container_name: bookstore-payment-service
    hostname: bookstore-payment-service
    ports:
      - "8001:8001"
    networks:
      - bookstore-app-network
    environment:
      - SERVER_PORT=8001
      - ZIPKIN_HOST=bookstore-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      labels:
        swarm.autoscaler: 'true'
        swarm.autoscaler.maximum: '4'
        swarm.autoscaler.minimum: '1'

volumes:
  bookstore-db-volume:
  bookstore-graphana-volume:
  booksture-telegraph-volume:
  booksture-influxdb-volume:
  booksture-chronograf-volume:

networks:
  bookstore-app-network:
    external: true
