global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['145.108.225.7:8080', '145.108.225.17:8080', '145.108.225.16:8080']
